# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- build
- test
- deploy
image:
  name: gcr.io/kaniko-project/executor:v1.9.1-debug
  entrypoint:
  - ''
variables:
  KANIKO_CACHE_ARGS: "--cache=true --cache-ttl=24h"
  VERSIONLABELMETHOD: OnlyIfThisCommitHasVersion
  IMAGE_LABELS: "--label com.gitlab.ci.tagorbranch=$CI_COMMIT_REF_NAME\n"
get-latest-git-version:
  stage: ".pre"
  image:
    name: alpine/git
    entrypoint:
    - ''
  rules:
  - if: $VERSIONLABELMETHOD == "LastVersionTagInGit"
  script:
  - |
    echo "the google kaniko container does not have git and does not have a packge manager to install it"
    git clone https://github.com/GoogleContainerTools/kaniko.git
    cd kaniko
    echo "$(git describe --abbrev=0 --tags)" > ../VERSIONTAG.txt
    echo "VERSIONTAG.txt contains $(cat ../VERSIONTAG.txt)"
  artifacts:
    paths:
    - VERSIONTAG.txt
".build_with_kaniko":
  stage: build
  script:
  - "echo \"Building and shipping image to $CI_REGISTRY_IMAGE\"\n#Build date for opencontainers\nBUILDDATE=\"'$(date
    '+%FT%T%z' | sed -E -n 's/(\\+[0-9]{2})([0-9]{2})$/\\1:\\2/p')'\" #rfc 3339 date\nIMAGE_LABELS=\"$IMAGE_LABELS
    --label org.opencontainers.image.created=$BUILDDATE --label build-date=$BUILDDATE\"\n#Description
    for opencontainers\nBUILDTITLE=$(echo $CI_PROJECT_TITLE | tr \" \" \"_\")\nIMAGE_LABELS=\"$IMAGE_LABELS
    --label org.opencontainers.image.title=$BUILDTITLE --label org.opencontainers.image.description=$BUILDTITLE\"\n#Add
    ref.name for opencontainers\nIMAGE_LABELS=\"$IMAGE_LABELS --label org.opencontainers.image.ref.name=$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME\"\n\n#Build
    Version Label and Tag from git tag, LastVersionTagInGit was placed by a previous
    job artifact\nif [[ \"$VERSIONLABELMETHOD\" == \"LastVersionTagInGit\" ]]; then
    VERSIONLABEL=$(cat VERSIONTAG.txt); fi\nif [[ \"$VERSIONLABELMETHOD\" == \"OnlyIfThisCommitHasVersion\"
    ]]; then VERSIONLABEL=$CI_COMMIT_TAG; fi\nif [[ ! -z \"$VERSIONLABEL\" ]]; then
    \n  IMAGE_LABELS=\"$IMAGE_LABELS --label org.opencontainers.image.version=$VERSIONLABEL\"\n
    \ ADDITIONALTAGLIST=\"$ADDITIONALTAGLIST $VERSIONLABEL\"\nfi\n\nADDITIONALTAGLIST=\"$ADDITIONALTAGLIST
    $CI_COMMIT_REF_NAME $CI_COMMIT_SHORT_SHA\"\nif [[ \"$CI_COMMIT_BRANCH\" == \"$CI_DEFAULT_BRANCH\"
    ]]; then ADDITIONALTAGLIST=\"$ADDITIONALTAGLIST latest\"; fi\nif [[ -n \"$ADDITIONALTAGLIST\"
    ]]; then \n  for TAG in $ADDITIONALTAGLIST; do \n    FORMATTEDTAGLIST=\"${FORMATTEDTAGLIST}
    --tag $CI_REGISTRY_IMAGE:$TAG \"; \n  done; \nfi\n\n#Reformat Docker tags to kaniko's
    --destination argument:\nFORMATTEDTAGLIST=$(echo \"${FORMATTEDTAGLIST}\" | sed
    s/\\-\\-tag/\\-\\-destination/g) \n\necho \"Kaniko arguments to run: --context
    $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile $KANIKO_CACHE_ARGS $FORMATTEDTAGLIST
    $IMAGE_LABELS\"\nmkdir -p /kaniko/.docker\necho \"{\\\"auths\\\":{\\\"$CI_REGISTRY\\\":{\\\"auth\\\":\\\"$(echo
    -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\\\"}}}\" > /kaniko/.docker/config.json\n/kaniko/executor
    --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile $KANIKO_CACHE_ARGS
    $FORMATTEDTAGLIST $IMAGE_LABELS\n"
build-for-gitlab-project-registry:
  extends: ".build_with_kaniko"
  environment:
    name: push-to-gitlab-project-registry
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
